export const configPlanetInfos = {
  gravity: ["Normal", "Light", "None", "Exteme"],
  color: ["blue", "red", "yellow", "orange", "purple", "black"],
  cabronDetected: [true, false],
  inhabited: [true, false],
  size: ["xs", "s", "m", "l", "xl", "xxl"],
  intelligenceFormsDetected: [true, false],
  name: [
    "Aldryss",
    "Khar’uun",
    "Tessarik",
    "Orvanel",
    "Drathuun",
    "Zeyphos",
    "Zerathis",
    "Orvella",
    "Nyxara",
    "Veloria",
    "Thalorin",
    "Crymara",
    "Xantheus",
    "Lunaris",
    "Solvion",
    "Aetheron",
    "Dravikos",
    "Pyrralis",
    "Kryndor",
    "Vossira",
    "Elunara",
    "Gravion",
    "Talvoria",
    "Ophirion",
    "Nexara",
    "Zyphora",
    "Caldris",
    "Vyntra",
    "Xerathis",
    "Lumoria",
    "Qythera",
    "Draxion",
    "Syralis",
    "Orlith",
    "Velkara",
    "Thrynos",
    "Calyth",
    "Zorvax",
    "Nythera",
    "Xylor",
    "Auralis",
    "Kryvos",
    "Virelia",
    "Elthar",
    "Gryndor",
    "Talyra",
    "Ophyria",
    "Nexion",
    "Zythera",
    "Calyon",
    "Vyxora",
    "Xandros",
    "Lumeth",
    "Qylaris",
    "Draxoria",
    "Sythera",
    "Orluna",
    "Velthar",
    "Thyros",
    "Calvoria",
    "Zoryn",
    "Nylara",
    "Xytheris",
    "Aurion",
    "Krythos",
    "Vireon",
    "Elvaris",
    "Grathis",
    "Talyon",
    "Ophion",
    "Nexora",
    "Zylaris",
    "Calythos",
    "Vyron",
    "Xandria",
    "Lumeris",
    "Qytherion",
    "Draxus",
    "Sylaris",
    "Orvion",
    "Velthos",
    "Thyraxis",
    "Calorin",
    "Zoryth",
    "Nylor",
    "Xylaria",
    "Aurionis",
    "Kryvax",
    "Vireth",
    "Eltharion",
    "Gravionis",
    "Talyth",
    "Ophyriax",
    "Nexionis",
    "Zytherion",
    "Calythia",
    "Vyxar",
    "Xandorion",
    "Lumethis",
    "Qylarion",
    "Draxaris",
    "Sytherion",
    "Orlunis",
    "Veltharia",
    "Thyrion",
    "Calvion",
    "Zorythia",
    "Nylthar",
    "Xythera",
    "Aurionix",
    "Krythoria",
    "Virelix",
    "Elvarion",
    "Grathion",
    "Talythos",
    "Ophirionis",
  ],
  observations: [
    "This planet has a dense atmosphere where light diffuses slowly, giving the impression of an eternal twilight.",
    "The surface is mostly rocky, marked by deep fractures from ancient tectonic activity.",
    "Temperatures vary strongly between hemispheres, suggesting a slow rotation and a highly tilted axis.",
    "Vast dark oceans cover the planet, reflecting little of the star it orbits.",
    "The atmosphere contains ionized particles producing auroras visible even during daylight.",
    "The planet seems devoid of complex life, though microorganisms might survive underground.",
    "Strong winds sculpt the terrain over millions of years, creating unique mineral formations.",
    "Gravity slightly stronger than Earth's makes every movement slower and heavier.",
    "An unstable magnetic field causes frequent orbital communication disturbances.",
    "The planet is covered by a mineral desert with bluish hues from rare oxides.",
    "Thick clouds block most sunlight, plunging the surface into permanent dimness.",
    "It orbits very close to its star, creating a scorching day side and frozen night side.",
    "Volcanic activity is still visible, regularly ejecting luminous plumes into the atmosphere.",
    "Polar regions are covered by ice rich in complex chemical compounds.",
    "The planet has a thin ring made of dust and rock fragments.",
    "Giant electrical storms sweep across the equator at regular intervals.",
    "The surface shows unexplained hexagonal patterns visible from orbit.",
    "This planet seems to be an ancient remnant of a lost star system.",
    "Nights are lit by diffuse atmospheric bioluminescence.",
    "The absence of liquid water makes the environment extremely hostile.",
    "The planet emits faint infrared radiation detectable from afar.",
    "Deep valleys suggest rivers once flowed here, now dried.",
    "The atmosphere is rich in methane, giving the sky an orange hue.",
    "The planet has chaotic rotation caused by strong gravitational interactions.",
    "The terrain appears artificially regular, though its origin remains unknown.",
    "A constant fog severely limits surface visibility.",
    "The planet has several moons strongly affecting tides.",
    "Climatic variations are extreme and unpredictable.",
    "This planet might have hosted an ancient civilization now gone.",
    "The soil consists of crystals that refract light unusually.",
    "Ongoing seismic activity makes the surface unstable.",
    "The planet is surrounded by a debris field from an ancient impact.",
    "Average temperatures theoretically allow liquid water to exist.",
    "The atmosphere is almost entirely composed of noble gases.",
    "The planet reflects very little light, making observation difficult.",
    "Vast plateaus dominate the overall topography.",
    "Day-night cycles are extremely long.",
    "The planet is in orbital resonance with neighboring bodies.",
    "Silent lightning frequently illuminates the clouds.",
    "The surface shows unusual greenish coloring.",
    "The planet is still forming, slowly accumulating matter.",
    "Magnetic poles are unstable and shift rapidly.",
    "High density suggests a massive metallic core.",
    "Natural radio emissions have been detected.",
    "The planet suffers constant erosion from its star.",
    "Reliefs are unusually smooth, like polished by time.",
    "The planet is isolated with no nearby major bodies.",
    "A faint glow sometimes surrounds the upper atmosphere.",
    "The planet displays giant radial fractures.",
    "Conditions are silent and motionless.",
    "The surface absorbs nearly all visible light.",
    "The planet has an extreme axial tilt.",
    "Natural structures resemble artificial ones.",
    "The planet is rich in rare metals.",
    "Supersonic winds dominate the atmosphere.",
    "The planet is plunged into almost permanent night.",
    "Dust storms regularly cover the surface.",
    "The planet seems frozen in an ancient state.",
    "Reliefs are dominated by immense canyons.",
    "The atmosphere is slowly escaping into space.",
    "The planet exhibits complex chemical activity.",
    "Light is diffused strangely across the surface.",
    "Temperature contrasts are violent.",
    "The planet is unstable in the long term.",
    "Observations remain difficult and incomplete.",
    "The planet possesses an austere, silent beauty.",
    "The ground is covered in volcanic ash.",
    "The planet is rich in heavy elements.",
    "Clouds form spiral patterns.",
    "The planet could be terraformed in the long run.",
    "Atmospheric variations are rapid.",
    "The planet shows a unique spectral signature.",
    "Nights are of absolute blackness.",
    "The planet seems to absorb sound.",
    "Reliefs change slowly over time.",
    "The planet is young on a cosmic scale.",
    "Unexplained luminous phenomena have been observed.",
    "The planet experiences strong radiation.",
    "Conditions are extreme but stable.",
    "The planet seems indifferent to the passage of time.",
    "Its landscape inspires both fear and fascination.",
    "This world has a mysterious, quiet charm.",
    "The horizon stretches endlessly, with shadows hinting at hidden valleys.",
    "Surface minerals shimmer subtly under starlight, revealing patterns only visible from orbit.",
    "Occasional dust devils move across plains, giving life to barren terrain.",
    "Mountain ranges rise sharply, their peaks catching faint light from distant stars.",
    "Thin ice sheets cover polar regions, reflecting pale light across the sky.",
    "The atmosphere produces soft glows at night, like a living aurora.",
    "Sparse vegetation-like structures hint at possible ancient ecosystems.",
    "Cratered landscapes tell stories of countless meteorite impacts over millennia.",
    "High cliffs create deep shadowed gorges, shaping the planet’s rugged topography.",
    "Streams of molten rock flow occasionally, glowing faintly under twilight skies.",
    "The planet’s rotation causes subtle changes in temperature across its surface.",
    "Vast plains stretch endlessly, broken only by scattered rocky outcrops.",
    "Rare storms sweep across deserts, momentarily illuminating dark horizons.",
    "Shimmering dust reflects faint starlight, creating a sense of motion even in stillness.",
    "The planet radiates a quiet, enigmatic energy visible to careful observers.",
  ],
  additionalName: ["I", "IV", "III", "x32", "p921"],
  letters: [
    "I",
    "II",
    "III",
    "IV",
    "V",
    "VI",
    "VII",
    "VIII",
    "IX",
    "X",
    "XII",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
  ],
  numbers: [0, 1, 2, 3],
  temperatureRanges: [
    { lava: [400, 1200] },
    { desert: [30, 80] },
    { earthLike: [-10, 35] },
    { ocean: [-2, 25] },
    { ice: [-220, -40] },
    { gas: [-150, -50] },
  ],
};
export const texturesArr = [
  "earth_clouds",
  "earth_night",
  "earth",
  "fic_1",
  "fic_2",
  "fic_3",
  "fic_4",
  "jupiter",
  "mars",
  "mercury",
  "milky_way",
  "moon",
  "neptune",
  "saturn",
  "saturn_ring",
  "stars",
  "sun",
  "uranus",
  "venus_at",
  "venus",
];
